# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/HARDWARE_ARCHI/HARDWARE_ARCHI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI || ORIG_REF_NAME==HARDWARE_ARCHI} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_microblaze_0_0 || ORIG_REF_NAME==HARDWARE_ARCHI_microblaze_0_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_dlmb_v10_0/HARDWARE_ARCHI_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_dlmb_v10_0 || ORIG_REF_NAME==HARDWARE_ARCHI_dlmb_v10_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_ilmb_v10_0/HARDWARE_ARCHI_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_ilmb_v10_0 || ORIG_REF_NAME==HARDWARE_ARCHI_ilmb_v10_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_dlmb_bram_if_cntlr_0/HARDWARE_ARCHI_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==HARDWARE_ARCHI_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_ilmb_bram_if_cntlr_0/HARDWARE_ARCHI_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==HARDWARE_ARCHI_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_lmb_bram_0/HARDWARE_ARCHI_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_lmb_bram_0 || ORIG_REF_NAME==HARDWARE_ARCHI_lmb_bram_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_xbar_0/HARDWARE_ARCHI_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_xbar_0 || ORIG_REF_NAME==HARDWARE_ARCHI_xbar_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_axi_periph_0/HARDWARE_ARCHI_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_microblaze_0_axi_periph_0 || ORIG_REF_NAME==HARDWARE_ARCHI_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_axi_intc_0/HARDWARE_ARCHI_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_microblaze_0_axi_intc_0 || ORIG_REF_NAME==HARDWARE_ARCHI_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_xlconcat_0/HARDWARE_ARCHI_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_microblaze_0_xlconcat_0 || ORIG_REF_NAME==HARDWARE_ARCHI_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_mdm_1_0/HARDWARE_ARCHI_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_mdm_1_0 || ORIG_REF_NAME==HARDWARE_ARCHI_mdm_1_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_clk_wiz_1_0/HARDWARE_ARCHI_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_clk_wiz_1_0 || ORIG_REF_NAME==HARDWARE_ARCHI_clk_wiz_1_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_rst_clk_wiz_1_100M_0/HARDWARE_ARCHI_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==HARDWARE_ARCHI_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_axi_uartlite_0_0/HARDWARE_ARCHI_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_axi_uartlite_0_0 || ORIG_REF_NAME==HARDWARE_ARCHI_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_axi_gpio_0_0/HARDWARE_ARCHI_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_axi_gpio_0_0 || ORIG_REF_NAME==HARDWARE_ARCHI_axi_gpio_0_0} -quiet] -quiet

# IP: bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_axi_iic_0_0/HARDWARE_ARCHI_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==HARDWARE_ARCHI_axi_iic_0_0 || ORIG_REF_NAME==HARDWARE_ARCHI_axi_iic_0_0} -quiet] -quiet

# XDC: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.gen/sources_1/bd/HARDWARE_ARCHI/HARDWARE_ARCHI_ooc.xdc
