# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/GABRUUU/Desktop/VSLI lab/VLSI_PROJ_MB_HW/VLSI_PROJ_MB_HW.srcs/sources_1/bd/MB_DESIGN/ip/MB_DESIGN_dlmb_v10_1/MB_DESIGN_dlmb_v10_1.xci
# IP: The module: 'MB_DESIGN_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/GABRUUU/Desktop/VSLI lab/VLSI_PROJ_MB_HW/VLSI_PROJ_MB_HW.gen/sources_1/bd/MB_DESIGN/ip/MB_DESIGN_dlmb_v10_1/MB_DESIGN_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_DESIGN_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/GABRUUU/Desktop/VSLI lab/VLSI_PROJ_MB_HW/VLSI_PROJ_MB_HW.srcs/sources_1/bd/MB_DESIGN/ip/MB_DESIGN_dlmb_v10_1/MB_DESIGN_dlmb_v10_1.xci
# IP: The module: 'MB_DESIGN_dlmb_v10_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/GABRUUU/Desktop/VSLI lab/VLSI_PROJ_MB_HW/VLSI_PROJ_MB_HW.gen/sources_1/bd/MB_DESIGN/ip/MB_DESIGN_dlmb_v10_1/MB_DESIGN_dlmb_v10_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_DESIGN_dlmb_v10_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
