# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/a7-100T.xdc

# Block Designs: bd/MB_DESIGN/MB_DESIGN.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN || ORIG_REF_NAME==MB_DESIGN} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_microblaze_0_1/MB_DESIGN_microblaze_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_microblaze_0_1 || ORIG_REF_NAME==MB_DESIGN_microblaze_0_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_dlmb_v10_1/MB_DESIGN_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_dlmb_v10_1 || ORIG_REF_NAME==MB_DESIGN_dlmb_v10_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_ilmb_v10_1/MB_DESIGN_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_ilmb_v10_1 || ORIG_REF_NAME==MB_DESIGN_ilmb_v10_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_dlmb_bram_if_cntlr_1/MB_DESIGN_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==MB_DESIGN_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_ilmb_bram_if_cntlr_1/MB_DESIGN_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==MB_DESIGN_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_lmb_bram_1/MB_DESIGN_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_lmb_bram_1 || ORIG_REF_NAME==MB_DESIGN_lmb_bram_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_xbar_0/MB_DESIGN_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_xbar_0 || ORIG_REF_NAME==MB_DESIGN_xbar_0} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_microblaze_0_axi_periph_0/MB_DESIGN_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_DESIGN_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_microblaze_0_axi_intc_0/MB_DESIGN_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MB_DESIGN_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_microblaze_0_xlconcat_0/MB_DESIGN_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_microblaze_0_xlconcat_0 || ORIG_REF_NAME==MB_DESIGN_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_mdm_1_1/MB_DESIGN_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_mdm_1_1 || ORIG_REF_NAME==MB_DESIGN_mdm_1_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_clk_wiz_1_1/MB_DESIGN_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_clk_wiz_1_1 || ORIG_REF_NAME==MB_DESIGN_clk_wiz_1_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_rst_clk_wiz_1_100M_1/MB_DESIGN_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==MB_DESIGN_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_axi_uartlite_0_0/MB_DESIGN_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_axi_uartlite_0_0 || ORIG_REF_NAME==MB_DESIGN_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_axi_gpio_0_1/MB_DESIGN_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_axi_gpio_0_1 || ORIG_REF_NAME==MB_DESIGN_axi_gpio_0_1} -quiet] -quiet

# IP: bd/MB_DESIGN/ip/MB_DESIGN_axi_iic_0_1/MB_DESIGN_axi_iic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB_DESIGN_axi_iic_0_1 || ORIG_REF_NAME==MB_DESIGN_axi_iic_0_1} -quiet] -quiet

# XDC: c:/Users/GABRUUU/Desktop/VSLI lab/VLSI_PROJ_MB_HW/VLSI_PROJ_MB_HW.gen/sources_1/bd/MB_DESIGN/MB_DESIGN_ooc.xdc
