# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.srcs/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0.xci
# IP: The module: 'HARDWARE_ARCHI_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.gen/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HARDWARE_ARCHI_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.gen/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'HARDWARE_ARCHI_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.gen/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HARDWARE_ARCHI_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.srcs/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0.xci
# IP: The module: 'HARDWARE_ARCHI_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.gen/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'HARDWARE_ARCHI_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.gen/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'HARDWARE_ARCHI_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/konev/Desktop/VLSI_PROJ_MB_HW_02/VLSI_PROJ_MB_HW_02.gen/sources_1/bd/HARDWARE_ARCHI/ip/HARDWARE_ARCHI_microblaze_0_0/HARDWARE_ARCHI_microblaze_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'HARDWARE_ARCHI_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
